/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.shogo82148.ribbonizer.plugin

import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.TaskProvider
import java.io.File
import java.util.*

class RibbonizerPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // add RibbonizerExtension
        project.extensions.add(RibbonizerExtension.NAME, RibbonizerExtension::class.java)

        val androidComponents = project.extensions.findByType(ApplicationAndroidComponentsExtension::class.java)
            ?: throw Exception("Not an Android application; you forget `apply plugin: 'com.android.application`?")
        val extension = project.extensions.findByType(RibbonizerExtension::class.java)!!

        // parse AndroidManifest
        val manifest = File(project.projectDir, "src/main/AndroidManifest.xml")
        val icons = Resources.launcherIcons(manifest)

        // find icon files
        val iconFiles = Resources.findResourceFiles(project.projectDir, icons)

        val tasks = mutableListOf<TaskProvider<RibbonizerTask>>()
        androidComponents.onVariants { variant ->
            // create a new task
            val capitalizedName = capitalize(variant.name)
            val name = "${RibbonizerTask.NAME}${capitalizedName}"
            val task = project.tasks.register(name, RibbonizerTask::class.java) {
                it.iconFiles.set(iconFiles)
            }
            variant.sources.res?.addGeneratedSourceDirectory(task, RibbonizerTask::outputDir)
            tasks.add(task)
        }
        project.task(mapOf("dependsOn" to tasks), RibbonizerTask.NAME)
    }
}

fun capitalize(string: String): String {
    return string.substring(0, 1).uppercase(Locale.ROOT) + string.substring(1)
}
