/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.shogo82148.ribbonizer.plugin

import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import org.gradle.api.Project
import org.gradle.api.Plugin
import java.util.*

class RibbonizerPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // add RibbonizerExtension
        project.extensions.add(RibbonizerExtension.NAME, RibbonizerExtension::class.java)

        val androidComponents = project.extensions.findByType(ApplicationAndroidComponentsExtension::class.java)
            ?: throw Exception("Not an Android application; you forget `apply plugin: 'com.android.application`?")
        val extension = project.extensions.findByType(RibbonizerExtension::class.java)!!

        androidComponents.onVariants { variant ->
            val capitalizedName = capitalize(variant.name)
            val name = "${RibbonizerTask.NAME}${capitalizedName}"
            val task = project.tasks.register(name, RibbonizerTask::class.java) {
            }
            variant.sources.res?.addGeneratedSourceDirectory(task, RibbonizerTask::outputDir)
        }
    }
}

fun capitalize(string: String): String {
    return string.substring(0, 1).uppercase(Locale.ROOT) + string.substring(1)
}
