version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: test
          command: |
            ./gradlew check
            ./gradlew ribbonize
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
