/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.shogo82148.ribbonizer

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.shogo82148.ribbonizer.greeting' plugin.
 */
class GradleAndroidRibbonizerPluginPluginFunctionalTest {
    @Test fun `can run task`() {
        // TODO: test me!
    }
}
