/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.shogo82148.ribbonizer

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.shogo82148.ribbonizer.greeting' plugin.
 */
class GradleAndroidRibbonizerPluginPluginTest {
    @Test fun `plugin registers task`() {
    }
}
